name: Build Zigscient Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: llogick/zigscient
          ref: dev
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build all targets
        run: |
          mkdir -p builds
          for target in "x86_64-linux-gnu" "aarch64-linux-gnu" "x86_64-windows" "aarch64-windows" "x86_64-macos" "aarch64-macos"; do
            zig build -Dtarget=${target} -Doptimize=ReleaseFast
            if [[ $target == *"windows"* ]]; then
              cp zig-out/bin/zigscient.exe builds/zigscient-${target}.exe
            else
              cp zig-out/bin/zigscient builds/zigscient-${target}
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: zigscient-release
          path: builds/
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zigscient-release
          path: zigscient-release
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Create zips
        run: |
          cd zigscient-release
          for file in *; do
            zip -j "../${file%.*}.zip" "$file"
          done
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: "*.zip"
